---
# System category - 28 test cases (0 implemented)
# Tags: system, SYS-ACC-001, SYS-CONN-001, SYS-CONSOLE-001, SYS-CFG-001, SYS-DEF-001, SYS-FLOW-001, SYS-FRR-001, SYS-HOST-001, SYS-IP-001, SYS-IPV6-001, SYS-LCD-001, SYS-LOGIN-001, SYS-LOGIN-002, SYS-NS-001, SYS-NS-002, SYS-OPT-001, SYS-OPT-002, SYS-PROXY-001, SYS-SFLOW-001, SYS-SYSCTL-001, SYS-SYSLOG-001, SYS-SYSLOG-002, SYS-SYSLOG-003, SYS-TASK-001, SYS-TZ-001, SYS-UPD-001, SYS-WDOG-001, SYS-ENC-001, SYS-ENC-002, SYS-ENC-003
#
# Pending:
# - sys_acc_001.yml (SYS-ACC-001: Offload/acceleration)
# - sys_conn_001.yml (SYS-CONN-001: Conntrack)
# - sys_console_001.yml (SYS-CONSOLE-001: Console device)
# - sys_cfg_001.yml (SYS-CFG-001: Config management)
# - sys_def_001.yml (SYS-DEF-001: Default route)
# - sys_flow_001.yml (SYS-FLOW-001: Flow accounting)
# - sys_frr_001.yml (SYS-FRR-001: FRR options)
# - sys_host_001.yml (SYS-HOST-001: Hostname)
# - sys_ip_001.yml (SYS-IP-001: System IP options)
# - sys_ipv6_001.yml (SYS-IPV6-001: System IPv6 options)
# - sys_lcd_001.yml (SYS-LCD-001: LCD display)
# - sys_login_001.yml (SYS-LOGIN-001: User login)
# - sys_login_002.yml (SYS-LOGIN-002: User level)
# - sys_ns_001.yml (SYS-NS-001: Name-server)
# - sys_ns_002.yml (SYS-NS-002: Domain search)
# - sys_opt_001.yml (SYS-OPT-001: System option)
# - sys_opt_002.yml (SYS-OPT-002: Startup beep)
# - sys_proxy_001.yml (SYS-PROXY-001: System proxy)
# - sys_sflow_001.yml (SYS-SFLOW-001: sFlow)
# - sys_sysctl_001.yml (SYS-SYSCTL-001: Sysctl)
# - sys_syslog_001.yml (SYS-SYSLOG-001: Syslog global)
# - sys_syslog_002.yml (SYS-SYSLOG-002: Syslog console/remote)
# - sys_syslog_003.yml (SYS-SYSLOG-003: Syslog TLS)
# - sys_task_001.yml (SYS-TASK-001: Task scheduler)
# - sys_tz_001.yml (SYS-TZ-001: Time zone)
# - sys_upd_001.yml (SYS-UPD-001: Image update)
# - sys_wdog_001.yml (SYS-WDOG-001: Watchdog)
# - sys_enc_001.yml (SYS-ENC-001: TPM config encryption enable)
# - sys_enc_002.yml (SYS-ENC-002: Encrypted config volume load)
# - sys_enc_003.yml (SYS-ENC-003: TPM encryption disable/recovery)
