---
# Service category - 26 test cases (0 implemented)
# Tags: service, SVC-BR-001, SVC-CFG-001, SVC-CONN-001, SVC-CONSOLE-001, SVC-DHCPR-001, SVC-DHCP-001, SVC-DHCP-002, SVC-DHCP-003, SVC-DNS-001, SVC-DNS-002, SVC-EVT-001, SVC-HTTPS-001, SVC-IPOE-001, SVC-LLDP-001, SVC-MDNS-001, SVC-MON-001, SVC-NTP-001, SVC-PPPOE-001, SVC-RA-001, SVC-SALT-001, SVC-SNMP-001, SVC-SSH-001, SVC-SSH-002, SVC-SURICATA-001, SVC-TFTP-001, SVC-WEBPROXY-001
#
# Pending:
# - svc_br_001.yml (SVC-BR-001: Broadcast relay)
# - svc_cfg_001.yml (SVC-CFG-001: Config sync)
# - svc_conn_001.yml (SVC-CONN-001: Conntrack sync)
# - svc_console_001.yml (SVC-CONSOLE-001: Console server)
# - svc_dhcpr_001.yml (SVC-DHCPR-001: DHCP relay)
# - svc_dhcp_001.yml (SVC-DHCP-001: DHCP server shared-network)
# - svc_dhcp_002.yml (SVC-DHCP-002: DHCP static mapping)
# - svc_dhcp_003.yml (SVC-DHCP-003: DHCP dynamic DNS)
# - svc_dns_001.yml (SVC-DNS-001: DNS forwarding)
# - svc_dns_002.yml (SVC-DNS-002: DNS cache and recursion)
# - svc_evt_001.yml (SVC-EVT-001: Event handler)
# - svc_https_001.yml (SVC-HTTPS-001: HTTPS API)
# - svc_ipoe_001.yml (SVC-IPOE-001: IPoE server)
# - svc_lldp_001.yml (SVC-LLDP-001: LLDP)
# - svc_mdns_001.yml (SVC-MDNS-001: mDNS reflector)
# - svc_mon_001.yml (SVC-MON-001: Monitoring export)
# - svc_ntp_001.yml (SVC-NTP-001: NTP server)
# - svc_pppoe_001.yml (SVC-PPPOE-001: PPPoE server)
# - svc_ra_001.yml (SVC-RA-001: Router advertisement)
# - svc_salt_001.yml (SVC-SALT-001: Salt minion)
# - svc_snmp_001.yml (SVC-SNMP-001: SNMP agent)
# - svc_ssh_001.yml (SVC-SSH-001: SSH service)
# - svc_ssh_002.yml (SVC-SSH-002: SSH key options)
# - svc_suricata_001.yml (SVC-SURICATA-001: Suricata IDS)
# - svc_tftp_001.yml (SVC-TFTP-001: TFTP server)
# - svc_webproxy_001.yml (SVC-WEBPROXY-001: Web proxy)
