router_id: "{{ r2_eth1_ip }}"

# Release verification: 2-node tests (pair_1)
rv_peer: r1
rv_underlay_ip: "{{ r2_eth1_ip }}"
rv_ipv6_underlay_ip: "fd00::2"
rv_dummy_ip: "{{ r2_dum0_ip }}"

# Per-test overlay IPs (r2 side)
rv_eth_test_ip: 10.30.0.2
rv_vlan_test_ip: 10.100.0.2
rv_tunnel_overlay_ip: 198.51.100.2
rv_geneve_overlay_ip: 198.51.110.2
rv_l2tpv3_overlay_ip: 198.51.111.2
rv_vti_overlay_ip: 198.51.112.2
rv_vxlan_overlay_ip: 198.51.120.2
rv_wg_overlay_ip: 10.10.10.2
rv_loop_test_ip: 192.0.2.202

interfaces:
#  - name: eth0
#    address: "{{ r2_eth0_ip }}"
#    prefix: 24
#    description: WAN
#    type: ethernet

  - name: eth1
    address: "{{ r2_eth1_ip }}"
    prefix: 24
    description: LAN
    type: ethernet

  - name: dum0
    address: "{{ r2_dum0_ip }}"
    prefix: 32
    description: conf-by-ansible
    type: dummy

ospf:
  networks:
    - "{{ routing.ospf.network }}"
    - "{{ r2_dum0_ip }}/32"

isis:
  net: 49.0001.1920.0200.0014.00
  interfaces:
    - eth1

bgp:
  neighbor: "{{ r1_eth1_ip }}"

vpn_ipsec:
  peer: RIGHT
  connection_type: initiate
  local_id: "{{ r2_eth1_ip }}"
  remote_id: "{{ r1_eth1_ip }}"
  interface: eth1
  peer_ip: "{{ r1_eth1_ip }}"
  psk: "1234567890"
  tunnels:
    - name: 1
      local_subnet: 100.64.11.0/24
      remote_subnet: 100.64.1.0/24
    - name: 2
      local_subnet: 100.64.22.0/24
      remote_subnet: 100.64.2.0/24
