---

- name: Add VRFs
  vyos.vyos.vyos_vrf:
    config:
      bind_to_all: true
      instances:
        - name: "green"
          description: "green-vrf"
          table_id: 111
          address_family:
            - afi: "ipv4"
              route_maps:
                - rm_name: "rm1"
                  protocol: "static"
                - rm_name: "rm1"
                  protocol: "ospf"

        - name: "red"
          description: "red-vrf"
          table_id: 112
